
var Module = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var da=Object.assign({},h),ea="./this.program",fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",ja,ka,la,fs,ma,na;
if(ia)p=ha?require("path").dirname(p)+"/":__dirname+"/",na=()=>{ma||(fs=require("fs"),ma=require("path"))},ja=function(a,b){na();a=ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a},ka=(a,b,c)=>{na();a=ma.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",
function(a){throw a;}),h.inspect=function(){return"[Emscripten Module object]"};else if(fa||ha)ha?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=h.print||console.log.bind(console),u=h.printErr||console.warn.bind(console);Object.assign(h,da);da=null;h.thisProgram&&(ea=h.thisProgram);var pa;h.wasmBinary&&(pa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");
var qa,ra=!1,sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function y(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var k=a.charCodeAt(++f);l=65536+((l&1023)<<10)|k&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Da,D,z,B,xa,C,E,Ea,Fa,Ga,Ha=[],Ia=[],Ja=[];function Ka(){var a=h.preRun.shift();Ha.unshift(a)}var F=0,La=null,Ma=null;
function w(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";u(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function Na(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="blsjs.wasm";if(!Na()){var Oa=G;G=h.locateFile?h.locateFile(Oa,p):p+Oa}function Pa(){var a=G;try{if(a==G&&pa)return new Uint8Array(pa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function Qa(){if(!pa&&(fa||ha)){if("function"==typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Pa()});if(ka)return new Promise(function(a,b){ka(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Pa()})}
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Ab;"number"==typeof c?void 0===b.Ga?Ga.get(c)():Ga.get(c)(b.Ga):c(void 0===b.Ga?null:b.Ga)}}}
function Sa(a){this.Z=a-24;this.cb=function(b){E[this.Z+4>>2]=b};this.ab=function(b){E[this.Z+8>>2]=b};this.Ya=function(){C[this.Z>>2]=0};this.$a=function(){D[this.Z+12>>0]=0};this.bb=function(){D[this.Z+13>>0]=0};this.sa=function(b,c){this.Za();this.cb(b);this.ab(c);this.Ya();this.$a();this.bb()};this.Za=function(){E[this.Z+16>>2]=0}}
var Ta=0,Ua=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Va=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ua(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Wa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Xa=
a=>{if("/"===a)return"/";a=Va(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Ya(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){w("randomDevice")}}
function Za(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ua(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var $a=[];function ab(a,b){$a[a]={input:[],output:[],wa:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.wa.flush(a.tty)},flush:function(a){a.tty.wa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.wa.Ta)throw new H(60);for(var e=0,f=0;f<d;f++){try{var l=a.tty.wa.Ta(a.tty)}catch(k){throw new H(29);}if(void 0===l&&0===e)throw new H(6);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.wa.Ja)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.wa.Ja(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},eb={Ta:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=db(b,!0)}return a.input.shift()},Ja:function(a,b){null===b||10===b?(oa(y(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(oa(y(a.output,0)),a.output=[])}},fb={Ja:function(a,b){null===b||10===b?(u(y(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(u(y(a.output,0)),a.output=[])}},I={ia:null,ma:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.ia||(I.ia={dir:{node:{na:I.Y.na,ja:I.Y.ja,lookup:I.Y.lookup,Ca:I.Y.Ca,rename:I.Y.rename,unlink:I.Y.unlink,rmdir:I.Y.rmdir,readdir:I.Y.readdir,symlink:I.Y.symlink},stream:{xa:I.aa.xa}},file:{node:{na:I.Y.na,ja:I.Y.ja},stream:{xa:I.aa.xa,read:I.aa.read,write:I.aa.write,Na:I.aa.Na,Ua:I.aa.Ua,Wa:I.aa.Wa}},link:{node:{na:I.Y.na,ja:I.Y.ja,readlink:I.Y.readlink},stream:{}},Oa:{node:{na:I.Y.na,ja:I.Y.ja},stream:gb}});c=hb(a,b,c,d);16384===(c.mode&
61440)?(c.Y=I.ia.dir.node,c.aa=I.ia.dir.stream,c.X={}):32768===(c.mode&61440)?(c.Y=I.ia.file.node,c.aa=I.ia.file.stream,c.ba=0,c.X=null):40960===(c.mode&61440)?(c.Y=I.ia.link.node,c.aa=I.ia.link.stream):8192===(c.mode&61440)&&(c.Y=I.ia.Oa.node,c.aa=I.ia.Oa.stream);c.timestamp=Date.now();a&&(a.X[b]=c,a.timestamp=c.timestamp);return c},Bb:function(a){return a.X?a.X.subarray?a.X.subarray(0,a.ba):new Uint8Array(a.X):new Uint8Array(0)},Qa:function(a,b){var c=a.X?a.X.length:0;c>=b||(b=Math.max(b,c*(1048576>
c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.X,a.X=new Uint8Array(b),0<a.ba&&a.X.set(c.subarray(0,a.ba),0))},sb:function(a,b){if(a.ba!=b)if(0==b)a.X=null,a.ba=0;else{var c=a.X;a.X=new Uint8Array(b);c&&a.X.set(c.subarray(0,Math.min(b,a.ba)));a.ba=b}},Y:{na:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ba:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;
b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.eb=4096;b.blocks=Math.ceil(b.size/b.eb);return b},ja:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.sb(a,b.size)},lookup:function(){throw ib[44];},Ca:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=jb(b,c)}catch(f){}if(d)for(var e in d.X)throw new H(55);}delete a.parent.X[a.name];a.parent.timestamp=
Date.now();a.name=c;b.X[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.X[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=jb(a,b),d;for(d in c.X)throw new H(55);delete a.X[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.X)a.X.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},aa:{read:function(a,b,
c,d,e){var f=a.node.X;if(e>=a.node.ba)return 0;a=Math.min(a.node.ba-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.X||a.X.subarray)){if(f)return a.X=b.subarray(c,c+d),a.ba=d;if(0===a.ba&&0===e)return a.X=b.slice(c,c+d),a.ba=d;if(e+d<=a.ba)return a.X.set(b.subarray(c,c+d),e),d}I.Qa(a,e+d);if(a.X.subarray&&b.subarray)a.X.set(b.subarray(c,c+d),e);else for(f=0;f<
d;f++)a.X[e+f]=b[c+f];a.ba=Math.max(a.ba,e+d);return d},xa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ba);if(0>b)throw new H(28);return b},Na:function(a,b,c){I.Qa(a.node,b+c);a.node.ba=Math.max(a.node.ba,b+c)},Ua:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.X;if(e&2||a.buffer!==Da){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;w();b=void 0;if(!b)throw new H(48);D.set(a,b)}else c=
!1,b=a.byteOffset;return{Z:b,zb:c}},Wa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.aa.write(a,b,0,d,c,!1);return 0}}},kb=null,lb={},K=[],mb=1,nb=null,ob=!0,H=null,ib={},L=(a,b={})=>{a=Za("/",a);if(!a)return{path:"",node:null};b=Object.assign({Sa:!0,Ka:0},b);if(8<b.Ka)throw new H(32);a=Ua(a.split("/").filter(l=>!!l),!1);for(var c=kb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=jb(c,a[e]);d=Va(d+"/"+a[e]);c.Da&&(!f||f&&b.Sa)&&(c=c.Da.root);
if(!f||b.Ra)for(f=0;40960===(c.mode&61440);)if(c=pb(d),d=Za(Wa(d),c),c=L(d,{Ka:b.Ka+1}).node,40<f++)throw new H(32);}return{path:d,node:c}},qb=a=>{for(var b;;){if(a===a.parent)return a=a.ma.Va,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},rb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length},jb=(a,b)=>{var c;if(c=(c=sb(a,"x"))?c:a.Y.lookup?0:2)throw new H(c,a);for(c=nb[rb(a.id,b)];c;c=c.nb){var d=c.name;if(c.parent.id===a.id&&
d===b)return c}return a.Y.lookup(a,b)},hb=(a,b,c,d)=>{a=new tb(a,b,c,d);b=rb(a.parent.id,a.name);a.nb=nb[b];return nb[b]=a},ub={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},vb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},sb=(a,b)=>{if(ob)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},wb=(a,b)=>{try{return jb(a,b),20}catch(c){}return sb(a,"wx")},xb=()=>{for(var a=0;4096>=a;a++)if(!K[a])return a;throw new H(33);
},zb=a=>{yb||(yb=function(){this.sa={}},yb.prototype={},Object.defineProperties(yb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.sa.flags},set:function(c){this.sa.flags=c}},position:{get:function(){return this.sa.position},set:function(c){this.sa.position=c}}}));a=Object.assign(new yb,a);var b=xb();a.fd=b;return K[b]=a},gb={open:a=>{a.aa=lb[a.node.rdev].aa;a.aa.open&&a.aa.open(a)},xa:()=>{throw new H(70);}},bb=(a,b)=>{lb[a]={aa:b}},
Ab=(a,b)=>{var c="/"===b,d=!b;if(c&&kb)throw new H(10);if(!c&&!d){var e=L(b,{Sa:!1});b=e.path;e=e.node;if(e.Da)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,Cb:{},Va:b,mb:[]};a=a.ma(b);a.ma=b;b.root=a;c?kb=a:e&&(e.Da=b,e.ma&&e.ma.mb.push(b))},M=(a,b,c)=>{var d=L(a,{parent:!0}).node;a=Xa(a);if(!a||"."===a||".."===a)throw new H(28);var e=wb(d,a);if(e)throw new H(e);if(!d.Y.Ca)throw new H(63);return d.Y.Ca(d,a,b,c)},Bb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);M(a,b|8192,c)},
Cb=(a,b)=>{if(!Za(a))throw new H(44);var c=L(b,{parent:!0}).node;if(!c)throw new H(44);b=Xa(b);var d=wb(c,b);if(d)throw new H(d);if(!c.Y.symlink)throw new H(63);c.Y.symlink(c,b,a)},pb=a=>{a=L(a).node;if(!a)throw new H(44);if(!a.Y.readlink)throw new H(28);return Za(qb(a.parent),a.Y.readlink(a))},Eb=(a,b,c)=>{if(""===a)throw new H(44);if("string"==typeof b){var d=ub[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==
typeof a)var e=a;else{a=Va(a);try{e=L(a,{Ra:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=M(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new H(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==vb(b)||b&512)?31:sb(e,vb(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?L(c,{Ra:!0}).node:c;if(!c.Y.ja)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==
(c.mode&61440))throw new H(28);if(d=sb(c,"w"))throw new H(d);c.Y.ja(c,{size:0,timestamp:Date.now()})}b&=-131713;e=zb({node:e,path:qb(e),flags:b,seekable:!0,position:0,aa:e.aa,Eb:[],error:!1});e.aa.open&&e.aa.open(e);!h.logReadFiles||b&1||(Db||(Db={}),a in Db||(Db[a]=1));return e},Fb=()=>{H||(H=function(a,b){this.node=b;this.tb=function(c){this.Ha=c};this.tb(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{ib[a]=new H(a);ib[a].stack="<generic error, no stack>"}))},
Gb,Hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Jb=(a,b,c)=>{a=Va("/dev/"+a);var d=Hb(!!b,!!c);Ib||(Ib=64);var e=Ib++<<8|0;bb(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,l,k,m)=>{for(var n=0,q=0;q<m;q++){try{var t=b()}catch(v){throw new H(29);}if(void 0===t&&0===n)throw new H(6);if(null===t||void 0===t)break;n++;l[k+q]=t}n&&(f.node.timestamp=Date.now());return n},write:(f,l,k,m)=>{for(var n=0;n<m;n++)try{c(l[k+n])}catch(q){throw new H(29);}m&&(f.node.timestamp=
Date.now());return n}});Bb(a,d,e)},Ib,Kb={},yb,Db,Lb=void 0;function Mb(a){a=K[a];if(!a)throw new H(8);return a}function Nb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ob=void 0;function N(a){for(var b="";z[a];)b+=Ob[z[a++]];return b}var O={},P={},Pb={};function Qb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Rb(a,b){a=Qb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Sb(a){var b=Error,c=Rb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Tb=void 0;function Q(a){throw new Tb(a);}var Ub=void 0;function Vb(a){throw new Ub(a);}function R(a,b,c){function d(k){k=c(k);k.length!==a.length&&Vb("Mismatched type converter count");for(var m=0;m<a.length;++m)S(a[m],k[m])}a.forEach(function(k){Pb[k]=b});var e=Array(b.length),f=[],l=0;b.forEach((k,m)=>{P.hasOwnProperty(k)?e[m]=P[k]:(f.push(k),O.hasOwnProperty(k)||(O[k]=[]),O[k].push(()=>{e[m]=P[k];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.kb)return;Q("Cannot register type '"+d+"' twice")}P[a]=b;delete Pb[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function Wb(a){Q(a.W.da.$.name+" instance already deleted")}var Xb=!1;function Yb(){}
function Zb(a){--a.count.value;0===a.count.value&&(a.fa?a.ga.pa(a.fa):a.da.$.pa(a.Z))}function $b(a,b,c){if(b===c)return a;if(void 0===c.ha)return null;a=$b(a,b,c.ha);return null===a?null:c.gb(a)}var ac={},bc=[];function cc(){for(;bc.length;){var a=bc.pop();a.W.ua=!1;a["delete"]()}}var dc=void 0,ec={};function fc(a,b){for(void 0===b&&Q("ptr should not be undefined");a.ha;)b=a.za(b),a=a.ha;return ec[b]}
function gc(a,b){b.da&&b.Z||Vb("makeClassHandle requires ptr and ptrType");!!b.ga!==!!b.fa&&Vb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return hc(Object.create(a,{W:{value:b}}))}function hc(a){if("undefined"===typeof FinalizationRegistry)return hc=b=>b,a;Xb=new FinalizationRegistry(b=>{Zb(b.W)});hc=b=>{var c=b.W;c.fa&&Xb.register(b,{W:c},b);return b};Yb=b=>{Xb.unregister(b)};return hc(a)}function T(){}
function ic(a,b,c){if(void 0===a[b].ea){var d=a[b];a[b]=function(){a[b].ea.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].ea+")!");return a[b].ea[arguments.length].apply(this,arguments)};a[b].ea=[];a[b].ea[d.ta]=d}}
function jc(a,b){h.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),ic(h,a,a),h.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].ea[void 0]=b):h[a]=b}function kc(a,b,c,d,e,f,l,k){this.name=a;this.constructor=b;this.va=c;this.pa=d;this.ha=e;this.hb=f;this.za=l;this.gb=k;this.pb=[]}
function lc(a,b,c){for(;b!==c;)b.za||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.za(a),b=b.ha;return a}function mc(a,b){if(null===b)return this.Ia&&Q("null is not a valid "+this.name),0;b.W||Q('Cannot pass "'+nc(b)+'" as a '+this.name);b.W.Z||Q("Cannot pass deleted object as a pointer of type "+this.name);return lc(b.W.Z,b.W.da.$,this.$)}
function oc(a,b){if(null===b){this.Ia&&Q("null is not a valid "+this.name);if(this.Ba){var c=this.qb();null!==a&&a.push(this.pa,c);return c}return 0}b.W||Q('Cannot pass "'+nc(b)+'" as a '+this.name);b.W.Z||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.Aa&&b.W.da.Aa&&Q("Cannot convert argument of type "+(b.W.ga?b.W.ga.name:b.W.da.name)+" to parameter type "+this.name);c=lc(b.W.Z,b.W.da.$,this.$);if(this.Ba)switch(void 0===b.W.fa&&Q("Passing raw pointer to smart pointer is illegal"),
this.ub){case 0:b.W.ga===this?c=b.W.fa:Q("Cannot convert argument of type "+(b.W.ga?b.W.ga.name:b.W.da.name)+" to parameter type "+this.name);break;case 1:c=b.W.fa;break;case 2:if(b.W.ga===this)c=b.W.fa;else{var d=b.clone();c=this.rb(c,U(function(){d["delete"]()}));null!==a&&a.push(this.pa,c)}break;default:Q("Unsupporting sharing policy")}return c}
function pc(a,b){if(null===b)return this.Ia&&Q("null is not a valid "+this.name),0;b.W||Q('Cannot pass "'+nc(b)+'" as a '+this.name);b.W.Z||Q("Cannot pass deleted object as a pointer of type "+this.name);b.W.da.Aa&&Q("Cannot convert argument of type "+b.W.da.name+" to parameter type "+this.name);return lc(b.W.Z,b.W.da.$,this.$)}function sc(a){return this.fromWireType(E[a>>2])}
function V(a,b,c,d){this.name=a;this.$=b;this.Ia=c;this.Aa=d;this.Ba=!1;this.pa=this.rb=this.qb=this.Xa=this.ub=this.ob=void 0;void 0!==b.ha?this.toWireType=oc:(this.toWireType=d?mc:pc,this.la=null)}function tc(a,b){h.hasOwnProperty(a)||Vb("Replacing nonexistant public symbol");h[a]=b;h[a].ta=void 0}
function uc(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Ga.get(b).apply(null,c);return d}}function W(a,b){a=N(a);var c=a.includes("j")?uc(a,b):Ga.get(b);"function"!=typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var vc=void 0;function wc(a){a=xc(a);var b=N(a);X(a);return b}
function yc(a,b){function c(f){e[f]||P[f]||(Pb[f]?Pb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new vc(a+": "+d.map(wc).join([", "]));}function zc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Rb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Ac(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Bc(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].la){k=!0;break}var m="void"!==b[0].name,n="",q="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Qb(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var t=k?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,Ac,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);l&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].la&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].la));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return zc(n).apply(null,d)}function Cc(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}var Dc=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ec(a){4<a&&0===--Y[a].La&&(Y[a]=void 0,Dc.push(a))}
var Z=a=>{a||Q("Cannot use deleted val. handle = "+a);return Y[a].value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Dc.length?Dc.pop():Y.length;Y[b]={La:1,value:a};return b}};function nc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Fc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ea[c>>2])};case 3:return function(c){return this.fromWireType(Fa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Gc(a,b,c){switch(b){case 0:return c?function(d){return D[d]}:function(d){return z[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return E[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Hc(a,b){var c=P[a];void 0===c&&Q(b+" has unknown type "+wc(a));return c}var Ic={};function Jc(a){var b=Ic[a];return void 0===b?N(a):b}var Kc=[];
function Lc(){return"object"==typeof globalThis?globalThis:Function("return this")()}function Mc(a){var b=Kc.length;Kc.push(a);return b}function Nc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Hc(E[b+4*d>>2],"parameter "+d);return c}var Oc=[],Pc={},Qc={};
function Rc(){if(!Sc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Qc)void 0===Qc[b]?delete a[b]:a[b]=Qc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sc=c}return Sc}var Sc;function Tc(a){return 0===a%4&&(0!==a%100||0===a%400)}var Uc=[31,29,31,30,31,30,31,31,30,31,30,31],Vc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Wc(a,b,c,d){function e(g,r,x){for(g="number"==typeof g?g.toString():g||"";g.length<r;)g=x[0]+g;return g}function f(g,r){return e(g,r,"0")}function l(g,r){function x(J){return 0>J?-1:0<J?1:0}var A;0===(A=x(g.getFullYear()-r.getFullYear()))&&0===(A=x(g.getMonth()-r.getMonth()))&&(A=x(g.getDate()-r.getDate()));return A}function k(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function m(g){var r=g.qa;for(g=new Date((new Date(g.ra+1900,0,1)).getTime());0<r;){var x=g.getMonth(),A=(Tc(g.getFullYear())?Uc:Vc)[x];if(r>A-g.getDate())r-=A-g.getDate()+1,g.setDate(1),11>x?g.setMonth(x+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+1));else{g.setDate(g.getDate()+r);break}}x=new Date(g.getFullYear()+1,0,4);r=k(new Date(g.getFullYear(),
0,4));x=k(x);return 0>=l(r,g)?0>=l(x,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var n=C[d+40>>2];d={xb:C[d>>2],wb:C[d+4>>2],Ea:C[d+8>>2],Ma:C[d+12>>2],Fa:C[d+16>>2],ra:C[d+20>>2],ka:C[d+24>>2],qa:C[d+28>>2],Db:C[d+32>>2],vb:C[d+36>>2],yb:n?n?y(z,n):"":""};c=c?y(z,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":function(g){return t[g.ka].substring(0,3)},"%A":function(g){return t[g.ka]},"%b":function(g){return v[g.Fa].substring(0,
3)},"%B":function(g){return v[g.Fa]},"%C":function(g){return f((g.ra+1900)/100|0,2)},"%d":function(g){return f(g.Ma,2)},"%e":function(g){return e(g.Ma,2," ")},"%g":function(g){return m(g).toString().substring(2)},"%G":function(g){return m(g)},"%H":function(g){return f(g.Ea,2)},"%I":function(g){g=g.Ea;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){for(var r=0,x=0;x<=g.Fa-1;r+=(Tc(g.ra+1900)?Uc:Vc)[x++]);return f(g.Ma+r,3)},"%m":function(g){return f(g.Fa+1,2)},"%M":function(g){return f(g.wb,
2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.Ea&&12>g.Ea?"AM":"PM"},"%S":function(g){return f(g.xb,2)},"%t":function(){return"\t"},"%u":function(g){return g.ka||7},"%U":function(g){return f(Math.floor((g.qa+7-g.ka)/7),2)},"%V":function(g){var r=Math.floor((g.qa+7-(g.ka+6)%7)/7);2>=(g.ka+371-g.qa-2)%7&&r++;if(r)53==r&&(x=(g.ka+371-g.qa)%7,4==x||3==x&&Tc(g.ra)||(r=1));else{r=52;var x=(g.ka+7-g.qa-1)%7;(4==x||5==x&&Tc(g.ra%400-1))&&r++}return f(r,2)},"%w":function(g){return g.ka},"%W":function(g){return f(Math.floor((g.qa+
7-(g.ka+6)%7)/7),2)},"%y":function(g){return(g.ra+1900).toString().substring(2)},"%Y":function(g){return g.ra+1900},"%z":function(g){g=g.vb;var r=0<=g;g=Math.abs(g)/60;return(r?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.yb},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=db(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}
function tb(a,b,c,d){a||(a=this);this.parent=a;this.ma=a.ma;this.Da=null;this.id=mb++;this.name=b;this.mode=c;this.Y={};this.aa={};this.rdev=d}Object.defineProperties(tb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Fb();nb=Array(4096);Ab(I,"/");M("/tmp",16895,0);M("/home",16895,0);M("/home/web_user",16895,0);
(()=>{M("/dev",16895,0);bb(259,{read:()=>0,write:(b,c,d,e)=>e});Bb("/dev/null",259);ab(1280,eb);ab(1536,fb);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=Ya();Jb("random",a);Jb("urandom",a);M("/dev/shm",16895,0);M("/dev/shm/tmp",16895,0)})();
(()=>{M("/proc",16895,0);var a=M("/proc/self",16895,0);M("/proc/self/fd",16895,0);Ab({ma:()=>{var b=hb(a,"fd",16895,73);b.Y={lookup:(c,d)=>{var e=K[+d];if(!e)throw new H(8);c={parent:null,ma:{Va:"fake"},Y:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var Xc=Array(256),Yc=0;256>Yc;++Yc)Xc[Yc]=String.fromCharCode(Yc);Ob=Xc;Tb=h.BindingError=Sb("BindingError");Ub=h.InternalError=Sb("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.W.da.$,c=this.W.Z,d=a.W.da.$;for(a=a.W.Z;b.ha;)c=b.za(c),b=b.ha;for(;d.ha;)a=d.za(a),d=d.ha;return b===d&&c===a};T.prototype.clone=function(){this.W.Z||Wb(this);if(this.W.ya)return this.W.count.value+=1,this;var a=hc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.W;a=a(c.call(b,d,{W:{value:{count:e.count,ua:e.ua,ya:e.ya,Z:e.Z,da:e.da,fa:e.fa,ga:e.ga}}}));a.W.count.value+=1;a.W.ua=!1;return a};
T.prototype["delete"]=function(){this.W.Z||Wb(this);this.W.ua&&!this.W.ya&&Q("Object already scheduled for deletion");Yb(this);Zb(this.W);this.W.ya||(this.W.fa=void 0,this.W.Z=void 0)};T.prototype.isDeleted=function(){return!this.W.Z};T.prototype.deleteLater=function(){this.W.Z||Wb(this);this.W.ua&&!this.W.ya&&Q("Object already scheduled for deletion");bc.push(this);1===bc.length&&dc&&dc(cc);this.W.ua=!0;return this};h.getInheritedInstanceCount=function(){return Object.keys(ec).length};
h.getLiveInheritedInstances=function(){var a=[],b;for(b in ec)ec.hasOwnProperty(b)&&a.push(ec[b]);return a};h.flushPendingDeletes=cc;h.setDelayFunction=function(a){dc=a;bc.length&&dc&&dc(cc)};V.prototype.ib=function(a){this.Xa&&(a=this.Xa(a));return a};V.prototype.Pa=function(a){this.pa&&this.pa(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=sc;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.Ba?gc(this.$.va,{da:this.ob,Z:c,ga:this,fa:a}):gc(this.$.va,{da:this,Z:a})}var c=this.ib(a);if(!c)return this.Pa(a),null;var d=fc(this.$,c);if(void 0!==d){if(0===d.W.count.value)return d.W.Z=c,d.W.fa=a,d.clone();d=d.clone();this.Pa(a);return d}d=this.$.hb(c);d=ac[d];if(!d)return b.call(this);d=this.Aa?d.fb:d.pointerType;var e=$b(c,this.$,d.$);return null===e?b.call(this):this.Ba?gc(d.$.va,{da:d,Z:e,ga:this,fa:a}):gc(d.$.va,{da:d,Z:e})};
vc=h.UnboundTypeError=Sb("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};function db(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var $c={e:function(a){return Zc(a+24)+24},d:function(a,b,c){(new Sa(a)).sa(b,c);Ta++;throw a;},C:function(a,b,c,d){Lb=d;try{b=b?y(z,b):"";var e=b;if("/"===e.charAt(0))b=e;else{if(-100===a)var f="/";else{var l=K[a];if(!l)throw new H(8);f=l.path}if(0==e.length)throw new H(44);b=Va(f+"/"+e)}if(d){Lb+=4;var k=C[Lb-4>>2]}else k=0;return Eb(b,c,k).fd}catch(m){if("undefined"==typeof Kb||!(m instanceof H))throw m;return-m.Ha}},w:function(){},F:function(a,b,c,d,e){var f=Nb(c);b=N(b);S(a,{name:b,fromWireType:function(l){return!!l},
toWireType:function(l,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=D;else if(2===c)k=B;else if(4===c)k=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>f])},la:null})},l:function(a,b,c,d,e,f,l,k,m,n,q,t,v){q=N(q);f=W(e,f);k&&(k=W(l,k));n&&(n=W(m,n));v=W(t,v);var g=Qb(q);jc(g,function(){yc("Cannot construct "+q+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var x=r.$;var A=x.va}else A=T.prototype;
r=Rb(g,function(){if(Object.getPrototypeOf(this)!==J)throw new Tb("Use 'new' to construct "+q);if(void 0===ca.oa)throw new Tb(q+" has no accessible constructor");var qc=ca.oa[arguments.length];if(void 0===qc)throw new Tb("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(ca.oa).toString()+") parameters instead!");return qc.apply(this,arguments)});var J=Object.create(A,{constructor:{value:r}});r.prototype=J;var ca=new kc(q,r,J,v,x,f,k,
n);x=new V(q,ca,!0,!1);A=new V(q+"*",ca,!1,!1);var rc=new V(q+" const*",ca,!1,!0);ac[a]={pointerType:A,fb:rc};tc(g,r);return[x,A,rc]})},b:function(a,b,c,d,e,f,l){var k=Cc(c,d);b=N(b);f=W(e,f);R([],[a],function(m){function n(){yc("Cannot call "+q+" due to unbound types",k)}m=m[0];var q=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=m.$.constructor;void 0===t[b]?(n.ta=c-1,t[b]=n):(ic(t,b,q),t[b].ea[c-1]=n);R([],k,function(v){v=[v[0],null].concat(v.slice(1));v=Bc(q,v,null,f,l);void 0===
t[b].ea?(v.ta=c-1,t[b]=v):t[b].ea[c-1]=v;return[]});return[]})},p:function(a,b,c,d,e,f,l,k){b=N(b);f=W(e,f);R([],[a],function(m){m=m[0];var n=m.name+"."+b,q={get:function(){yc("Cannot access "+n+" due to unbound types",[c])},enumerable:!0,configurable:!0};q.set=k?()=>{yc("Cannot access "+n+" due to unbound types",[c])}:()=>{Q(n+" is a read-only property")};Object.defineProperty(m.$.constructor,b,q);R([],[c],function(t){t=t[0];var v={get:function(){return t.fromWireType(f(d))},enumerable:!0};k&&(k=
W(l,k),v.set=g=>{var r=[];k(d,t.toWireType(r,g));Ac(r)});Object.defineProperty(m.$.constructor,b,v);return[]});return[]})},r:function(a,b,c,d,e,f){0<b||w();var l=Cc(b,c);e=W(d,e);R([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.$.oa&&(k.$.oa=[]);if(void 0!==k.$.oa[b-1])throw new Tb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
k.$.oa[b-1]=()=>{yc("Cannot construct "+k.name+" due to unbound types",l)};R([],l,function(n){n.splice(1,0,null);k.$.oa[b-1]=Bc(m,n,null,e,f);return[]});return[]})},f:function(a,b,c,d,e,f,l,k){var m=Cc(c,d);b=N(b);f=W(e,f);R([],[a],function(n){function q(){yc("Cannot call "+t+" due to unbound types",m)}n=n[0];var t=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.$.pb.push(b);var v=n.$.va,g=v[b];void 0===g||void 0===g.ea&&g.className!==n.name&&g.ta===c-2?(q.ta=c-2,q.className=n.name,
v[b]=q):(ic(v,b,t),v[b].ea[c-2]=q);R([],m,function(r){r=Bc(t,r,n,f,l);void 0===v[b].ea?(r.ta=c-2,v[b]=r):v[b].ea[c-2]=r;return[]});return[]})},E:function(a,b){b=N(b);S(a,{name:b,fromWireType:function(c){var d=Z(c);Ec(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:sc,la:null})},t:function(a,b,c){c=Nb(c);b=N(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Fc(b,c),la:null})},k:function(a,
b,c,d,e){b=N(b);-1===e&&(e=4294967295);e=Nb(c);var f=k=>k;if(0===d){var l=32-8*c;f=k=>k<<l>>>l}c=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};S(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Gc(b,e,0!==d),la:null})},g:function(a,b,c){function d(f){f>>=2;var l=E;return new e(Da,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{kb:!0})},s:function(a,b){b=N(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=E[d>>2];if(c)for(var f=d+4,l=0;l<=e;++l){var k=d+4+l;if(l==e||0==z[k]){f=f?y(z,f,k-f):"";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=k+1}}else{m=Array(e);for(l=0;l<e;++l)m[l]=String.fromCharCode(z[d+4+l]);m=m.join("")}X(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof
Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var l=(c&&f?()=>ua(e):()=>e.length)(),k=Zc(4+l+1);E[k>>2]=l;if(c&&f)ta(e,z,k+4,l+1);else if(f)for(f=0;f<l;++f){var m=e.charCodeAt(f);255<m&&(X(k),Q("String has UTF-16 code units that do not fit in 8 bits"));z[k+4+f]=m}else for(f=0;f<l;++f)z[k+4+f]=e[f];null!==d&&d.push(X,k);return k},argPackAdvance:8,readValueFromPointer:sc,la:function(d){X(d)}})},o:function(a,b,c){c=N(c);if(2===b){var d=wa;var e=ya;var f=za;var l=
()=>xa;var k=1}else 4===b&&(d=Aa,e=Ba,f=Ca,l=()=>E,k=2);S(a,{name:c,fromWireType:function(m){for(var n=E[m>>2],q=l(),t,v=m+4,g=0;g<=n;++g){var r=m+4+g*b;if(g==n||0==q[r>>k])v=d(v,r-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=r+b}X(m);return t},toWireType:function(m,n){"string"!=typeof n&&Q("Cannot pass non-string to C++ string type "+c);var q=f(n),t=Zc(4+q+b);E[t>>2]=q>>k;e(n,t+4,q+b);null!==m&&m.push(X,t);return t},argPackAdvance:8,readValueFromPointer:sc,la:function(m){X(m)}})},G:function(a,
b){b=N(b);S(a,{lb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},i:function(a,b,c){a=Z(a);b=Hc(b,"emval::as");var d=[],e=U(d);C[c>>2]=e;return b.toWireType(d,a)},H:function(a,b,c,d,e){a=Kc[a];b=Z(b);c=Jc(c);var f=[];C[d>>2]=U(f);return a(b,c,f,e)},I:function(a,b,c,d){a=Kc[a];b=Z(b);c=Jc(c);a(b,c,null,d)},a:Ec,v:function(a){if(0===a)return U(Lc());a=Jc(a);return U(Lc()[a])},u:function(a,b){var c=Nc(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(q){return q.name}).join("_")+
"$";var e=Oc[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],l="",k=0;k<a-1;++k)l+=(0!==k?", ":"")+"arg"+k,e.push("argType"+k),f.push(c[1+k]);var m="return function "+Qb("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(k=0;k<a-1;++k)m+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[k+1].argPackAdvance;m+="    var rv = handle[name]("+l+");\n";for(k=0;k<a-1;++k)c[k+1].deleteObject&&(m+="    argType"+k+".deleteObject(arg"+k+");\n");d.lb||
(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=zc(e).apply(null,f);e=Mc(a);return Oc[b]=e},j:function(a,b){a=Z(a);b=Z(b);return U(a[b])},c:function(a){4<a&&(Y[a].La+=1)},J:function(a,b,c,d){a=Z(a);var e=Pc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)l+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+
f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","valueToHandle",l+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(Hc,h,U);Pc[b]=e}return e(a,c,d)},m:function(a){return U(Jc(a))},h:function(a){var b=Z(a);Ac(b);Ec(a)},n:function(a,b){a=Hc(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},q:function(){w("")},A:function(){w("OOM")},y:function(a,b){var c=0;Rc().forEach(function(d,
e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>0]=d.charCodeAt(f);D[e>>0]=0;c+=d.length+1});return 0},z:function(a,b){var c=Rc();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},D:function(a){try{var b=Mb(a);if(null===b.fd)throw new H(8);b.jb&&(b.jb=null);try{b.aa.close&&b.aa.close(b)}catch(c){throw c;}finally{K[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Kb||!(c instanceof H))throw c;return c.Ha}},B:function(a,b,c,d){try{a:{var e=Mb(a);
a=b;for(var f=b=0;f<c;f++){var l=E[a>>2],k=E[a+4>>2];a+=8;var m=e,n=l,q=k,t=void 0,v=D;if(0>q||0>t)throw new H(28);if(null===m.fd)throw new H(8);if(1===(m.flags&2097155))throw new H(8);if(16384===(m.node.mode&61440))throw new H(31);if(!m.aa.read)throw new H(28);var g="undefined"!=typeof t;if(!g)t=m.position;else if(!m.seekable)throw new H(70);var r=m.aa.read(m,v,n,q,t);g||(m.position+=r);var x=r;if(0>x){var A=-1;break a}b+=x;if(x<k)break}A=b}C[d>>2]=A;return 0}catch(J){if("undefined"==typeof Kb||
!(J instanceof H))throw J;return J.Ha}},x:function(a,b,c,d){return Wc(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;qa=h.asm.K;Da=e=qa.buffer;h.HEAP8=D=new Int8Array(e);h.HEAP16=B=new Int16Array(e);h.HEAP32=C=new Int32Array(e);h.HEAPU8=z=new Uint8Array(e);h.HEAPU16=xa=new Uint16Array(e);h.HEAPU32=E=new Uint32Array(e);h.HEAPF32=Ea=new Float32Array(e);h.HEAPF64=Fa=new Float64Array(e);Ga=h.asm.N;Ia.unshift(h.asm.L);F--;h.monitorRunDependencies&&h.monitorRunDependencies(F);0==F&&(null!==La&&(clearInterval(La),La=null),Ma&&(e=Ma,Ma=null,e()))}function b(e){a(e.instance)}function c(e){return Qa().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){u("failed to asynchronously prepare wasm: "+f);w(f)})}var d={a:$c};F++;h.monitorRunDependencies&&h.monitorRunDependencies(F);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return u("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||"function"!=typeof WebAssembly.instantiateStreaming||Na()||G.startsWith("file://")||ia||"function"!=typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){u("wasm streaming compile failed: "+f);u("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.L).apply(null,arguments)};var Zc=h._malloc=function(){return(Zc=h._malloc=h.asm.M).apply(null,arguments)},X=h._free=function(){return(X=h._free=h.asm.O).apply(null,arguments)},xc=h.___getTypeName=function(){return(xc=h.___getTypeName=h.asm.P).apply(null,arguments)};
h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.Q).apply(null,arguments)};h.___cxa_is_pointer_type=function(){return(h.___cxa_is_pointer_type=h.asm.R).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.S).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.T).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.U).apply(null,arguments)};
h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.V).apply(null,arguments)};var ad;Ma=function bd(){ad||cd();ad||(Ma=bd)};
function cd(){function a(){if(!ad&&(ad=!0,h.calledRun=!0,!ra)){h.noFSInit||Gb||(Gb=!0,Fb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Jb("stdin",h.stdin):Cb("/dev/tty","/dev/stdin"),h.stdout?Jb("stdout",null,h.stdout):Cb("/dev/tty","/dev/stdout"),h.stderr?Jb("stderr",null,h.stderr):Cb("/dev/tty1","/dev/stderr"),Eb("/dev/stdin",0),Eb("/dev/stdout",1),Eb("/dev/stderr",1));ob=!1;Ra(Ia);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ja.unshift(b)}Ra(Ja)}}if(!(0<F)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ka();Ra(Ha);0<F||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=cd;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();cd();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
